[project]
name = "chaserland-api-gateway"
version = "0.1.0"
description = ""
authors = [{ name = "ChaserZ98", email = "feiyuzheng98@gmail.com" }]
readme = "README.md"
requires-python = ">=3.12, <4"
dependencies = [
    "fastapi (>=0.115.12,<0.116.0)",
    "pydantic-settings (>=2.8.1,<3.0.0)",
    "redis (>=5.2.1,<6.0.0)",
    "uvicorn (>=0.34.0,<0.35.0)",
    "chaserland-grpc-proto @ git+https://github.com/ChaserZ98/chaserland-grpc-proto.git@v0.2.0",
    "chaserland-common @ git+https://github.com/ChaserZ98/chaserland-common@dev",
]

[tool.poetry]
packages = [{ include = "chaserland_api_gateway", from = "src" }]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
